branch-defaults:
  master:
    environment: eb-dev
    group_suffix: null
global:
  application_name: parse_eb
  default_ec2_keyname: yick_key
  default_platform: Node.js
  default_region: ap-southeast-1
  profile: eb-cli
  sc: git
